export const myTraits = [
    { label: 'Charismatique', value: 1, options: [] },
    { label: 'Intelligent', value: 2, options: [] },
    { label: 'Audacieux', value: 3, options: [] },
    { label: 'Honnête', value: 4, options: [] },
    { label: 'Égoïste', value: 5, options: [] },
    { label: 'Courageux', value: 6, options: [] },
    { label: 'Mystérieux', value: 7, options: [] },
    { label: 'Loyal', value: 8, options: [] },
    { label: 'Manipulateur', value: 9, options: [] },
    { label: 'Sage', value: 10, options: [] },
    { label: 'Impulsif', value: 11, options: [] },
    { label: 'Bienveillant', value: 12, options: [] },
    { label: 'Sociable', value: 13, options: [] },
    { label: 'Solitaire', value: 14, options: [] },
    { label: 'Aventureux', value: 15, options: [] },
    { label: 'Calculateur', value: 16, options: [] },
    { label: 'Idéaliste', value: 17, options: [] },
    { label: 'Excentrique', value: 18, options: [] },
    { label: 'Déterminé', value: 19, options: [] },
    { label: 'Noble', value: 20, options: [] },
    { label: 'Sarcastique', value: 21, options: [] },
    { label: 'Sensible', value: 22, options: [] },
    { label: 'Intrépide', value: 23, options: [] },
    { label: 'Perfectionniste', value: 24, options: [] },
    { label: 'Humble', value: 25, options: [] },
    { label: 'Curieux', value: 26, options: [] },
    { label: 'Impatient', value: 27, options: [] },
    { label: 'Généreux', value: 28, options: [] },
    { label: 'Imperturbable', value: 29, options: [] },
    { label: 'Créatif', value: 30, options: [], },
];

export const mySkills = [
    { label: 'Analyse de données', value: 1, options: [] },
    { label: 'Botanique', value: 2, options: [] },
    { label: 'Bureaucratie du CHOM', value: 3, options: [] },
    { label: 'Chirurgie', value: 4, options: [] },
    { label: 'Contrebande', value: 5, options: [] },
    { label: 'Cultures', value: 6, options: [] },
    { label: 'Déductions', value: 7, options: [] },
    { label: 'Ecologie', value: 8, options: [] },
    { label: 'Etiquette', value: 9, options: [] },
    { label: 'Géologie', value: 10, options: [] },
    { label: 'Kanly', value: 11, options: [] },
    { label: 'Langage corporel', value: 12, options: [] },
    { label: 'Maladies infectieuses', value: 13, options: [] },
    { label: `Médecine d'urgence`, value: 14, options: [] },
    { label: 'Philosophie', value: 15, options: [] },
    { label: 'Physique', value: 16, options: [], },
    { label: 'Pièges', value: 17, options: [] },
    { label: 'Poisons', value: 18, options: [] },
    { label: 'Politique des maisons', value: 19, options: [] },
    { label: 'Politique impériale', value: 20, options: [] },
    { label: 'Psychiatrie', value: 21, options: [] },
    { label: 'Religion', value: 22, options: [] },
    { label: 'Sixième sens', value: 23, options: [] },
    { label: 'Technologie de pointe', value: 24, options: [] },
    { label: 'Virologie', value: 25, options: [] }
];